name: flutter_azimuth_example
description: Demonstrates how to use the flutter_azimuth plugin.



publish_to: 'none' 

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_azimuth:
    path: ../

  cupertino_icons: ^1.0.2
  video_player: ^2.4.7

flutter_native_splash:
  color: "#000000"
  image: assets/icon-dark.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^2.2.9

flutter_icons:
  image_path: "assets/icon-dark.png" 
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#FF771089"
  adaptive_icon_foreground: assets/icon-dark.png
flutter:

  uses-material-design: true

  assets:
    - assets/
 